### PR TITLE
AE-4245 Ago is 1 day long for years, months, weeks.

### PR DESCRIPTION
**Pull request by pgan002**
Part 2 of https://iamplus.atlassian.net/browse/AE-4245.

### CODE REVIEW

**Comment by justonj** [comment]
(# ___ ago ) is the whole day. The day should be from midnight to midnight, it's not an exact time range based on query time.

**Review by dpathania1 — APPROVED** [review]

**Comment by pgan002** [comment]
Closing this until https://github.com/iAmPlus/timestring/pull/19 is merged.

**Comment by pgan002** [comment]
Re-open after #23 is merged, rebased here and I re-run tests on this branch.

**Comment by pgan002** [comment]
Closing in favor of https://github.com/iAmPlus/timestring/pull/25

**Pull request closed without merging**
