### PR TITLE
Add timezone support to tester script

### PR DESCRIPTION
**Pull request by pleasantone**
Add a '-z/--zone' option to allow for easier testing of mistakes in dealing with timezones in the code.

### CODE REVIEW

**Comment by pgan002** [comment]
What's the use case?

**Comment by pleasantone** [comment]
Testing that part of the code.

**Comment by pgan002** [comment]
Can you be more explicit? What part of the code? Why do you need a timezone command line parameter to test it? I run tests like `pytest tests/tests.py tests/test_range.py`; how do you run them?

**Comment by pleasantone** [comment]
The change is just to the “standalone” portion of the code that is used for non automated developer testing before we create the formal tests. It simply gives the user the ability to set the tz parameter in the calls when doing testing from the command line. If you don’t specify it, there are no changes from normal. This change is trivial.

**Comment by pgan002** [comment]
Yes, the change is trivial and would be useful beyond testing and development if it worked. `python timestring` does not work for me. How do you use your change?

**Comment by pleasantone** [comment]
setup.py installs an executable called timestring:

entry_points={'console_scripts': ['timestring=timestring:main']})


$ timestring -z utc today
From 09/19/17 00:00:00 to 09/20/17 00:00:00

**Comment by pgan002** [comment]
Oh, got it.

**Pull request merged**
